#!/usr/bin/env perl

#既存の格子をちょっとだけ拡張する。例えば、単位格子の2x2x2倍の格子を3x3x3倍に変換したりする場合に、1.5 1.5 1.5という引数を与えればよいようにする。
#2倍までの任意の実数に対応

sub rint{
    local($_)=@_;
    if($_>0){
	int($_+0.5);
    }elsif($_<0){
	#これは厳密には正しくない。許せ。
	int($_-0.5);
    }else{
	0;
    }
}


die "usage: $0 xratio yratio zratio\n" if $#ARGV!=2;
($mulx,$muly,$mulz)=@ARGV;

while(<STDIN>){
    if(/\@BXLA/){
	$bxl=<STDIN>;
	$bx=$by=$bz=$bxl;
	print "\@BOX3\n";
	print $bx*$mulx," ",$by*$muly," ",$bz*$mulz,"\n";
    }elsif(/\@BOX3/){
	print;
	$_=<STDIN>;
	($bx,$by,$bz)=split;
	print $bx*$mulx," ",$by*$muly," ",$bz*$mulz,"\n";
    }elsif(/\@NX3A/||/\@NX4A/||/\@AR3A/||/\@WTG6/){
        print;
        $n=<STDIN>;
	$c=0;
	$o="";
	$nbx=$bx*$mulx;
	$nby=$by*$muly;
	$nbz=$bz*$mulz;
        $x=$y=$z=0.0;
        for($i=0;$i<$n;$i++){
            $line=<STDIN>;
            $lines[$i]=$line;
            @_=split(/ +/,$line,9999);
            while ($_[0] eq ''){shift(@_);}
	    $x=$_[0]-rint($_[0]/$bx)*$bx+0.5*$bx;
	    $y=$_[1]-rint($_[1]/$by)*$by+0.5*$by;
	    $z=$_[2]-rint($_[2]/$bz)*$bz+0.5*$bz;
	    for($xx=0;$xx<$mulx;$xx++){
		for($yy=0;$yy<$muly;$yy++){
		    for($zz=0;$zz<$mulz;$zz++){
			$_[0]=$x+$xx*$bx;
			$_[1]=$y+$yy*$by;
			$_[2]=$z+$zz*$bz;
			if(($_[0]<$nbx)&&($_[1]<$nby)&&($_[2]<$nbz)){
			    $o.=join(' ',@_);
			    if($#_==2){$o.="\n";}
			    $c++;
			}
		    }
		}
	    }
	}
	print "$c\n$o";
    }
    else{
        print;
    }
}

